"""job_supp_id

Revision ID: 4bc0ee6be99d
Revises: bdb807641fc2
Create Date: 2024-08-21 22:40:22.783767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc0ee6be99d'
down_revision = 'bdb807641fc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IGS_JOB_SUPPORT', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'IGS_JOB_SUPPORT', 'IGS_USERS', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'IGS_JOB_SUPPORT', type_='foreignkey')
    op.drop_column('IGS_JOB_SUPPORT', 'user_id')
    # ### end Alembic commands ###
