"""start_date and followup_date deleted

Revision ID: 5aa38cfeab54
Revises: ba154e97bd74
Create Date: 2024-08-21 23:36:47.413344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa38cfeab54'
down_revision = 'ba154e97bd74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('IGS_JOB_SUPPORT', 'followup_date')
    op.drop_column('IGS_JOB_SUPPORT', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IGS_JOB_SUPPORT', sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('IGS_JOB_SUPPORT', sa.Column('followup_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
