"""Describe your changes here

Revision ID: 6068f3696fbe
Revises: da86e7d74f6f
Create Date: 2024-08-13 01:21:31.958716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6068f3696fbe'
down_revision = 'da86e7d74f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
