"""course enquiry

Revision ID: 70cb79acceed
Revises: 6068f3696fbe
Create Date: 2024-08-19 18:34:03.802127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cb79acceed'
down_revision = '6068f3696fbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
