"""start_date and followup_date again Updated

Revision ID: 908df63cae92
Revises: 5aa38cfeab54
Create Date: 2024-08-21 23:37:52.490850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908df63cae92'
down_revision = '5aa38cfeab54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IGS_JOB_SUPPORT', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('IGS_JOB_SUPPORT', sa.Column('followup_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('IGS_JOB_SUPPORT', 'followup_date')
    op.drop_column('IGS_JOB_SUPPORT', 'start_date')
    # ### end Alembic commands ###
