"""user_id for course-enquiry

Revision ID: bdb807641fc2
Revises: df98ba2ff38c
Create Date: 2024-08-21 02:23:39.788065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb807641fc2'
down_revision = 'df98ba2ff38c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IGS_COURSE_ENQUIRY', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'IGS_COURSE_ENQUIRY', 'IGS_USERS', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'IGS_COURSE_ENQUIRY', type_='foreignkey')
    op.drop_column('IGS_COURSE_ENQUIRY', 'user_id')
    # ### end Alembic commands ###
