"""start_date and followyp_date

Revision ID: cc56eaf7a0c6
Revises: 4bc0ee6be99d
Create Date: 2024-08-21 23:28:10.027188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc56eaf7a0c6'
down_revision = '4bc0ee6be99d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
