"""role_id for users

Revision ID: df98ba2ff38c
Revises: f427f20361d4
Create Date: 2024-08-21 01:39:43.860153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df98ba2ff38c'
down_revision = 'f427f20361d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IGS_USERS', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'IGS_USERS', 'IGS_USER_ROLE', ['role_id'], ['role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'IGS_USERS', type_='foreignkey')
    op.drop_column('IGS_USERS', 'role_id')
    # ### end Alembic commands ###
